[4pt] [BACKEND] Generate Models based on the diagram#16
romans-adi/travel-booking-backend pull request #23
Opened 2023-09-22 20:07 UTC by MMGGYY66

## [[4pt] [BACKEND] Generate Models based on the diagram#16](https://github.com/romans-adi/travel-booking-backend/issues/16)

2023-09-23 02:28 UTC, carreraprogrammer requested changes
## Hi @MMGGYY66  :wave: 
Good job so far!
There are some issues that you still need to work on but you are almost there!

![so-close](https://github.com/carreraprogrammer/y_recipes/assets/93520178/411197c9-ee62-40f0-a88b-f2461010ac87)

## Highlights
- [x] Nice UI :+1: 
- [x] Registration and login implemented with devise :+1: 
- [x] Associations between models were made correctly :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-23 02:28 UTC, carreraprogrammer commented on app/models/travel.rb
> +  belongs_to :place
I kindly recommend you to change the relation between the tables. Place belongs_to :travel, but Travel has one place like this

has_one :place

That is gonna improve the reliability and Conventionally, in Rails, a belongs_to association is used in the model that "owns" the foreign key, while has_one is used in the model that doesn't own the foreign key.

2023-09-23 02:28 UTC, carreraprogrammer commented on app/models/travel.rb
> +end
I kindly recommend you to add the :trough relation, because reservations table is a linked table

has_many :travels, through: :reservations

This can help to make more abstractions and have access to useful methods

2023-09-23 02:28 UTC, carreraprogrammer commented on app/models/user.rb
> +
As in the travels model, it could be usefull to clarify the has many through relation between User and Travel

has_many :users, through: :reservations

2023-09-23 19:38 UTC, MMGGYY66 commented on app/models/travel.rb
> +end
done but it does not to be has_many :travels, through: :reservations
because it is travels table 
so it has to be :   has_many :places, through: :reservations

2023-09-23 19:40 UTC, MMGGYY66 commented on app/models/user.rb
> +
done with correction :   has_many :travels, through: :reservations

2023-09-24 14:53 UTC, carreraprogrammer commented
Hi @MMGGYY66.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights

:heavy_check_mark: good work implementing changes?

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-24 18:49 UTC, merged