Traveli: Reservation Controller Improvements
romans-adi/travel-booking-backend pull request #29
Opened 2023-10-01 03:27 UTC by romans-adi

For this PR these minor updates were implemented:

- The `before_action` method with `:authenticate_user!` is used as a `filter` to ensure that the user making requests to these endpoints `is authenticated`.
- The `index` action fetches all `reservations` associated with the `current authenticated user` (`current_user.reservations`).
- The create action is responsible for creating a `new reservation` (booking). It initializes a new `Reservation object` with parameters from `reservation_params` and sets the `user_id` attribute of the reservation to the ID of the `current authenticated user`. If the reservation is successfully saved, it renders the created reservation in JSON format with a status code of 201 (Created).
- The `destroy` action deletes a specific reservation based on the provided `id` parameter.

2023-10-01 15:51 UTC, carreraprogrammer commented on app/controllers/api/v1/reservations_controller.rb
> +before_action :authenticate_user!
Hello, the controller is not properly written, I think you deleted the line 1

class Api::V1::ReservationsController < ApplicationController

2023-10-01 16:11 UTC, carreraprogrammer commented on app/controllers/api/v1/reservations_controller.rb
> +  @reservations = current_user.reservations
As I told you in the front-end review, it could be a great idea to include the travels and places information in this request to avoid too many server requests. This is my idea

@reservations = current_user.reservations.include(:travel, travel: [:places])

Do you think is worth?

2023-10-01 16:16 UTC, carreraprogrammer requested changes
Hi @romans-adi,

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next part, but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-02 22:14 UTC, romans-adi commented on app/controllers/api/v1/reservations_controller.rb
> +before_action :authenticate_user!
This typo was fixed! Thank you for being attentive!

2023-10-03 02:15 UTC, carreraprogrammer commented
# Approved! :medal_sports: 

Hi @romans-adi, 

Your part in the project is complete! :shipit:
Congratulations! :rocket:
 
<img src="https://media.tenor.com/xDHCe07zrocAAAAC/congrats-minions.gif"/>

## Highlights

- [x]  All linters passed
- [x] Great work implementing the changes

Cheers, and Happy coding!👏👏👏
***
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-03 02:15 UTC, merged